"""empty message

Revision ID: 0055a38345a5
Revises: 510423f391a7
Create Date: 2024-05-13 13:14:32.516938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0055a38345a5'
down_revision = '510423f391a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betaregistration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('betaregistration')
    # ### end Alembic commands ###
