# Generated by Django 4.2.11 on 2024-05-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("release", models.IntegerField(default=0)),
            ],
        ),
    ]
