# Generated by Django 4.2.11 on 2024-05-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ashish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="id",
            field=models.AutoField(default=1001, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
